### 1) 생성
다음은 파이토치에서 텐서를 생성하고 연산하는 예제입니다.

In [1]:
import torch

# 1차원 텐서 생성
x = torch.tensor([1, 2, 3])
print(x)

tensor([1, 2, 3])


In [3]:
# 2차원 텐서 생성
y = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
# 모든 원소가 0인 3차원 텐서 생성
z = torch.zeros((2, 3, 4))
print(z)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [7]:
# 모든 원소가 1인 4차원 텐서 생성
w = torch.ones((2, 2, 2, 2))
print(w)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [8]:
# 랜덤한 값으로 채워진 3x3 텐서 생성
r = torch.rand((3, 3))
print(r)

tensor([[0.4434, 0.6059, 0.8538],
        [0.4884, 0.5181, 0.4541],
        [0.0078, 0.3777, 0.0765]])


위 예제에서는 torch.tensor() 함수를 사용하여 텐서를 생성했습니다. torch.tensor() 함수는 파이썬 리스트나 넘파이 배열을 입력받아 텐서를 생성합니다.

이외에도, torch.zeros(), torch.ones(), torch.rand() 함수를 사용하여 모든 원소가 0, 1 또는 랜덤한 값으로 채워진 텐서를 생성할 수 있습니다. 인자로 텐서의 크기를 입력합니다.


텐서의 크기를 입력해 텐서를 얻는 여러 방법이 있는데 그 중 많이 쓰이는 방법 몇 개를 더 소개하려 합니다.

앞에서 소개한 .rand 함수는 균등 분포(uniform distribution)에서 난수를 생성합니다. 이 분포는 최솟값과 최댓값 사이의 값들이 동일한 확률로 선택되는 분포입니다.

비슷한 함수로 .randn 함수는 정규 분포(normal distribution)에서 난수를 생성합니다. 이 분포는 대표적인 연속 확률 분포로, 평균(mean)과 분산(variance)을 가지는 범위에서 난수를 생성합니다. 정규 분포는 자연계에서 많이 발견되며, 중심 극한 정리에 따라 다른 분포로 근사할 수 있습니다.

따라서, .rand 함수는 0과 1 사이의 값이 동일한 확률로 선택되는 무작위 값을 생성하고, .randn 함수는 평균 0, 분산 1인 정규 분포에서 무작위 값을 생성합니다

In [9]:
import torch

# 균등 분포에서 난수 생성
x = torch.rand((2, 3))
print(x)

# 정규 분포에서 난수 생성
y = torch.randn((2, 3))
print(y)


tensor([[0.3647, 0.3798, 0.3252],
        [0.8856, 0.4037, 0.3675]])
tensor([[ 0.2688, -0.4276,  1.0313],
        [ 1.4401,  0.0733, -0.4702]])


.Tensor나 .empty 함수는 메모리 상에 할당된 임의의 값으로 초기화된 텐서를 생성합니다.

In [10]:
# .Tensor 예제1
a = torch.Tensor([1, 2, 3])
print(a)

# .empty 예제
b = torch.empty(2, 3)
print(b)

# .Tensor 예제2
c = torch.Tensor(2,3)
print(c)


tensor([1., 2., 3.])
tensor([[-5.7806e-34,  1.3663e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[-5.7807e-34,  1.3663e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


이 장에서 처음 소개한 소문자로 시작하는 .tensor와는 다르게 대문자로 시작하는 .Tensor는 기본적으로 FloatTensor와 동일하며(이외에도 정수형 텐서를 만드는 IntTensor, Bool형 텐서를 만드는 BoolTensor가 있습니다.) 입력된 데이터를 실수형 텐서로 만들거나 empty나 rand, randn처럼 텐서의 크기를 입력해 새로운 텐서를 만들 수도 있습니다.