# 1. tensor

파이토치(PyTorch)에서 텐서(Tensor)는 다차원 배열을 나타내는 자료형입니다. 넘파이(Numpy)의 ndarray와 유사한 API를 제공하며, GPU를 이용한 연산도 지원합니다. 텐서를 사용하여 머신러닝 모델에서 데이터를 표현하고 연산을 수행합니다.

tensor 메서드는 파이썬 리스트나 넘파이 배열을 PyTorch 텐서로 변환해주는 역할을 합니다. 이 메서드는 다음과 같이 사용됩니다.

In [4]:
import torch 
# data = [[1,2,3], [4,5,6]]

torch.tensor(data, dtype=None, device=None, requires_grad=False)


tensor([[1, 2, 3],
        [4, 5, 6]])

- data: 텐서로 변환하고자 하는 데이터입니다. 파이썬 리스트나 넘파이 배열 등이 사용될 수 있습니다.
- dtype (optional): 텐서의 데이터 타입을 지정합니다. 기본값은 None으로, 자동으로 데이터 타입을 인식합니다.
- device (optional): 텐서가 사용될 디바이스를 지정합니다. 기본값은 None으로, CPU 상에서 계산됩니다.
- requires_grad (optional): 해당 텐서가 그래디언트를 계산할지 여부를 지정합니다. 기본값은 False입니다.

예를 들어, 다음과 같이 파이썬 리스트를 텐서로 변환할 수 있습니다

In [5]:
import torch

data = [[1,2,3], [4,5,6]]
x = torch.tensor(data, dtype=torch.float32)
print(x)
tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[1., 2., 3.],
        [4., 5., 6.]])


NameError: name 'tensor' is not defined